//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing.Framework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.BlobStorageMetaDatas = new HashSet<BlobStorageMetaData>();
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string MetaData { get; set; }
    
        public virtual ICollection<BlobStorageMetaData> BlobStorageMetaDatas { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
