//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacturing.Framework.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManufacturingModelContainer : DbContext
    {
        public ManufacturingModelContainer()
            : base("name=ManufacturingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<BlobStorageMetaData> BlobStorageMetaDatas { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventTypes> EventTypes1 { get; set; }
    }
}
